version: '3.8'

services:
  nginxui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asuswrt-merlin-nginxui
    ports:
      - "8080:80"
    volumes:
      - ./config:/etc/nginxui
      - ./logs:/var/log/nginxui
      - ./data:/var/lib/nginxui
      - /etc/nginx:/etc/nginx:ro
    environment:
      - NODE_ENV=production
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    networks:
      - nginxui-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a development service
  nginxui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: asuswrt-merlin-nginxui-dev
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3000
    command: npm run dev
    profiles:
      - dev
    networks:
      - nginxui-network

networks:
  nginxui-network:
    driver: bridge

volumes:
  nginxui-config:
  nginxui-logs:
  nginxui-data: