name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels:
  - "enhancement"
  - "triage"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        
        Before submitting, please:
        - Search existing issues to see if this has been requested
        - Check if this feature aligns with the project goals
        - Consider if this could be implemented as a plugin or extension

  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I have also considered...
    validations:
      required: false

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - User Interface (UI/UX)
        - Nginx Configuration
        - SSL/TLS Management
        - Load Balancing
        - Monitoring & Logging
        - Security
        - Performance
        - API/Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor change or addition
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Unknown - Not sure about complexity
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help.
      placeholder: |
        In my setup, I need to...
        This feature would help by...
        The benefit would be...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or examples to help explain your feature request.
      placeholder: Drag and drop images here or paste them

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical considerations, requirements, or implementation ideas.
      placeholder: |
        Technical requirements:
        - ...
        
        Implementation ideas:
        - ...
        
        Potential challenges:
        - ...

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Please check all that apply
      options:
        - label: This feature should work on all supported router models
        - label: This feature may require specific router capabilities
        - label: This feature should be backward compatible
        - label: This feature may require breaking changes

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request here.
      placeholder: |
        Related links:
        - ...
        
        Similar implementations:
        - ...
        
        Additional notes:
        - ...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I would be willing to help implement this feature
        - label: I would be willing to test this feature
        - label: I would be willing to help with documentation
        - label: I would be willing to provide feedback during development

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please check the following before submitting
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have provided a clear description of the feature
          required: true
        - label: I have explained the use case and benefits
          required: true